# Default configuration for TaspiaSB Plugin
# Define rewards and block unlocks for each level here
levels:
  # Level 5: Basic blocks and minion reward
  5:
    minion:
      name: "&f1x &eMiner Minion"
      material: PLAYER_HEAD
      command: "minions give %player% minion"
    island-block-unlocks:
      - IRON_BLOCK
      - ENCHANTING_TABLE
      - ANVIL
      - CHIPPED_ANVIL
      - DAMAGED_ANVIL
  
  # Level 10: Valuable blocks and rewards
  10:
    golden_apples:
      name: "&f3x &eGolden Apples"
      material: GOLDEN_APPLE
      command: "minecraft:give %player% golden_apple 3"
    stone:
      name: "&f3x &eStone Blocks"
      material: STONE
      command: "minecraft:give %player% stone 3"
    island-block-unlocks:
      - DIAMOND_BLOCK
      - BREWING_STAND
      
  # Level 15: Advanced blocks
  15:
    island-block-unlocks:
      - CONDUIT
      - BEACON
      
  # Level 20: Rare blocks  
  20:
    island-block-unlocks:
      - EMERALD_BLOCK
      
  # Level 25: Premium blocks
  25:
    island-block-unlocks:
      - NETHERITE_BLOCK
      
  # Level 50: Ultra rare blocks
  50:
    island-block-unlocks:
      - DRAGON_EGG
      
  # Add more levels and rewards as needed

# MySQL Database Configuration for AlonsoLevels fallback
mysql:
  # Enable MySQL fallback for offline players
  enabled: true
  
  # Database connection details
  host: "localhost"
  port: 3306
  database: "alonsolevels"
  username: "your_username"
  password: "your_password"
  
  # Table name for player levels
  table_name: "alonsoskyblock_users"
  
  # Connection pool settings
  pool:
    maximum_pool_size: 10
    minimum_idle: 2
    connection_timeout: 30000
    idle_timeout: 600000
    max_lifetime: 1800000

# You can add other plugin-wide configurations below
